"""adding the todo table

Revision ID: 4f26c9c416e0
Revises: e67cc958ef77
Create Date: 2022-10-20 17:23:29.036815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f26c9c416e0'
down_revision = 'e67cc958ef77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('content', sa.String(length=120), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_content'), 'todo', ['content'], unique=False)
    op.create_index(op.f('ix_todo_creation_date'), 'todo', ['creation_date'], unique=False)
    op.create_index(op.f('ix_todo_title'), 'todo', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_title'), table_name='todo')
    op.drop_index(op.f('ix_todo_creation_date'), table_name='todo')
    op.drop_index(op.f('ix_todo_content'), table_name='todo')
    op.drop_table('todo')
    # ### end Alembic commands ###
